name: Main
on: 
  workflow_dispatch
jobs:
  Run01:
    name: Main 01
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.1]
        flag: [A, B, C, D, E]
    env:
        NUM_JOBS: 5
        JOB: ${{ matrix.go }}
    defaults:
     run:
       shell: wsl-bash -u root {0}   
    steps:
    - name: set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: setup
      uses: Vampire/setup-wsl@v1
      with:
          use-cache: 'false'
  Run02:   
    name: Main 02   
    needs: Run01  
    runs-on: windows-latest
    timeout-minutes: 35
    strategy:   
      max-parallel: 10   
      fail-fast: false   
      matrix:   
        go: [1.1, 1.2, 1.3]   
        flag: [A, B, C, D, E]   
    env:   
        NUM_JOBS: 30   
        JOB: ${{ matrix.go }}   
    defaults:   
     run:   
       shell: wsl-bash -u root {0}   
    steps:   
    - name: Ready Go ${{ matrix.go }}  
      uses: actions/setup-go@v1   
      with:   
        go-version: ${{ matrix.go }}   
      id: go   
    - name: Setup 01   
      uses: Vampire/setup-wsl@v1
    - name : Setup 02
      run: apt-get update && apt-get upgrade -y && apt-get install -y wget unzip
    - name: Setup 03
      run: echo "Hello Word"
